//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhsachbacsi
    {
        public string mabacsi { get; set; }
        public string hovaten { get; set; }
        public string chucvu { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public string cmnd { get; set; }
    }
}
