//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datlichhen
    {
        public string maKhamBenh { get; set; }
        public string hoVaTen { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public string ngayThangNamSinh { get; set; }
        public string gioiTinh { get; set; }
        public string ngayHen { get; set; }
        public string noiDung { get; set; }
        public string trangThai { get; set; }
        public string IdTaiKhoan { get; set; }
    }
}
