//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAIKHOAN
    {
        public string HOTEN { get; set; }

        [Required(ErrorMessage = "Hãy nhập thông tin ngày sinh hợp lệ")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string SODT { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string MATKHAU { get; set; }
        public string IDTAIKHOAN { get; set; }
        public string IDCHUCVU { get; set; }
        public string LoginErrorMessage { get; internal set; }
        public string LoginSuccessMessage { get; internal set; }
    }
}
